version: "3.8"
services:
  backend:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=user
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - db
  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "user"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_HOST: "localhost"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
