export const plantContactMap = {
  AEROESPACIAL: "Lic. Jesús Elías",
  "BD HMO": "Lic. Dayanne Montaño",
  Cpp: "Lic. Roxana Osuna",
  "EDS HMO": "Ing. Ricardo Sobarzo",
  "EDS MAGDALENA": "Ing. Ricardo Sobarzo",
  "ILS HMO": "Lic. Heriberto Acedo",
  INDUSTRIAL: "Ing. Gabriela Soto",
  INTEC: "Alejandrina Corona",
  "LATECOERE LMXA": "Lizbeth Rodríguez",
  "LATECOERE LMXC": "Miranda Tinoco Carranza",
  "LATECOERE LMXD": "Laura Dávila",
  "LATELEC LMXB": "Yoselin Huerta",
  "LEONI LABOR": "Claudia Grijalva",
  "LEONI QUIROGA": "Claudia Grijalva",
  PXG: "Alejo Sarmiento",
  "TE 02": "Ing. Aarón Hernández",
  "TE 04": "Ing. Aarón Hernández",
  "TE 05": "Ing. Aarón Hernández",
  "TE 875": "Ing. Norman Vázquez",
  "TE ALMACEN DELTA ICT": "Ing. Aarón Hernández",
  "TE AUTOMOTRIZ": "Ing: Héctor Sicre",
  "TE GLOG": "Lic. Alberto Sánchez",
  "TE ICT": "Ing. Aarón Hernández",
  "TE MEDICAL": "Ing. Manuel Zazueta",
  "TE ML1": "Lic. Alberto Sánchez",
  "TE SENSORES": "Ing. Luis Armando Martínez",
  "Yarda Nogales": "Lic. Roxana Osuna",
};

export default plantContactMap;
